export const COMMAND_CATALOG_B: { cat: string; cmds: { name: string; desc: string }[] }[] = [
  { cat: "لینوکس — سوکت و فایروال", cmds: [
    { name: "ss -tuln", desc: "سوکت‌های listen" },
    { name: "ss -s", desc: "آمار سوکت" },
    { name: "ss -tunap", desc: "با PID و process" },
    { name: "ss -ltn", desc: "TCP listen" },
    { name: "ss -lun", desc: "UDP listen" },
    { name: "netstat -tuln", desc: "netstat قدیمی" },
    { name: "netstat -anp", desc: "با process" },
    { name: "lsof -i", desc: "پورت‌های باز" },
    { name: "lsof -i :80", desc: "پورت خاص" },
    { name: "iptables -L", desc: "قوانین iptables" },
    { name: "iptables -L -n -v", desc: "جزئیات iptables" },
    { name: "iptables -S", desc: "قوانین به صورت -A" },
    { name: "nft list ruleset", desc: "nftables" },
    { name: "firewall-cmd --list-all", desc: "firewalld" },
    { name: "firewall-cmd --state", desc: "وضعیت firewalld" },
    { name: "ufw status", desc: "وضعیت UFW" },
    { name: "ufw status verbose", desc: "UFW جزئیات" },
    { name: "ufw allow", desc: "اجازه پورت" },
    { name: "ufw deny", desc: "مسدود پورت" },
  ]},
  { cat: "لینوکس — NetworkManager و سرویس", cmds: [
    { name: "nmcli", desc: "NetworkManager CLI" },
    { name: "nmcli device", desc: "دستگاه‌ها" },
    { name: "nmcli device status", desc: "وضعیت دستگاه" },
    { name: "nmcli connection", desc: "اتصالات" },
    { name: "nmcli connection show", desc: "لیست connection" },
    { name: "nmcli networking", desc: "وضعیت networking" },
    { name: "nmtui", desc: "TUI NetworkManager" },
    { name: "systemctl status NetworkManager", desc: "سرویس NM" },
    { name: "systemctl status systemd-networkd", desc: "networkd" },
    { name: "systemctl status sshd", desc: "SSH" },
    { name: "systemctl status nginx", desc: "nginx" },
    { name: "hostnamectl", desc: "نام و OS" },
    { name: "uname -a", desc: "کرنل و معماری" },
    { name: "uptime", desc: "زمان روشن بودن" },
  ]},
  { cat: "لینوکس — capture و ابزار پیشرفته", cmds: [
    { name: "tcpdump", desc: "capture پکت" },
    { name: "tcpdump -i eth0", desc: "روی eth0" },
    { name: "tcpdump -i any port 53", desc: "DNS traffic" },
    { name: "tcpdump -n", desc: "بدون resolve" },
    { name: "tcpdump -c 10", desc: "۱۰ پکت" },
    { name: "wireshark", desc: "تحلیلگر GUI" },
    { name: "tshark", desc: "Wireshark CLI" },
    { name: "curl -I", desc: "هدر HTTP" },
    { name: "curl -v", desc: "verbose HTTP" },
    { name: "wget", desc: "دانلود" },
    { name: "nc -zv", desc: "تست پورت (netcat)" },
    { name: "ncat", desc: "ncat" },
    { name: "nmap", desc: "اسکن پورت" },
    { name: "nmap -sT", desc: "TCP connect scan" },
    { name: "nmap -p 80,443", desc: "پورت‌های خاص" },
    { name: "iperf3", desc: "تست پهنای باند" },
    { name: "iperf3 -c", desc: "کلاینت iperf" },
    { name: "iperf3 -s", desc: "سرور iperf" },
    { name: "bridge link", desc: "bridge" },
    { name: "brctl show", desc: "bridge قدیمی" },
    { name: "iwconfig", desc: "وای‌فای قدیمی" },
    { name: "iw dev", desc: "وای‌فای جدید" },
    { name: "iwlist scan", desc: "اسکن Wi-Fi" },
  ]},
  { cat: "لینوکس — فایل‌های شبکه", cmds: [
    { name: "cat /etc/network/interfaces", desc: "interfaces (Debian)" },
    { name: "cat /etc/netplan/*.yaml", desc: "netplan (Ubuntu)" },
    { name: "cat /etc/sysconfig/network-scripts/ifcfg-eth0", desc: "ifcfg (RHEL)" },
    { name: "cat /proc/net/dev", desc: "آمار کرنل" },
    { name: "cat /proc/net/route", desc: "روت کرنل" },
    { name: "cat /proc/net/arp", desc: "ARP کرنل" },
    { name: "sysctl net.ipv4.ip_forward", desc: "IP forwarding" },
    { name: "sysctl -a | grep forward", desc: "forward settings" },
  ]},
  { cat: "ویندوز تکمیلی A", cmds: [
    { name: "ping -w", desc: "timeout" },
    { name: "tracert -h", desc: "max hops" },
    { name: "tracert -w", desc: "timeout" },
    { name: "tracert -4", desc: "IPv4" },
    { name: "tracert -6", desc: "IPv6" },
    { name: "pathping -n", desc: "no resolve" },
    { name: "pathping -h", desc: "max hops" },
    { name: "pathping -q", desc: "queries" },
    { name: "arp -g", desc: "ARP table" },
    { name: "route -p", desc: "persistent" },
    { name: "netstat -n", desc: "numeric" },
    { name: "netstat -o", desc: "PID" },
    { name: "netstat -ab", desc: "apps" },
    { name: "netstat -es", desc: "full stats" },
    { name: "net share C$", desc: "admin share" },
    { name: "net use /delete", desc: "unmap" },
    { name: "net user administrator", desc: "admin user" },
    { name: "net localgroup users", desc: "Users" },
    { name: "net session /delete", desc: "drop session" },
    { name: "net statistics server", desc: "server stats" },
    { name: "net config server", desc: "server config" },
    { name: "net pause", desc: "pause service" },
    { name: "net continue", desc: "continue" },
    { name: "net file", desc: "open files" },
    { name: "net group", desc: "domain groups" },
    { name: "net print", desc: "printers" },
    { name: "net helpmsg", desc: "error msg" },
    { name: "net name", desc: "computer names" },
    { name: "nbtstat -A", desc: "by IP" },
    { name: "nbtstat -s", desc: "sessions" },
    { name: "nbtstat -S", desc: "sessions IP" },
    { name: "Get-DnsClientGlobalSetting", desc: "DNS global" },
    { name: "Set-DnsClientGlobalSetting", desc: "set DNS global" },
    { name: "Get-DnsClientNrptPolicy", desc: "NRPT" },
    { name: "Get-NetAdapter -Name", desc: "adapter by name" },
    { name: "Get-NetAdapterAdvancedProperty", desc: "NIC advanced" },
    { name: "Rename-NetAdapter", desc: "rename" },
    { name: "Set-NetIPInterface", desc: "set IP iface" },
    { name: "Get-NetFirewallAddressFilter", desc: "addr filter" },
    { name: "Get-NetFirewallPortFilter", desc: "port filter" },
    { name: "Get-NetFirewallApplicationFilter", desc: "app filter" },
    { name: "Set-NetConnectionProfile", desc: "set profile" },
    { name: "Get-SmbMapping", desc: "SMB maps" },
    { name: "New-SmbMapping", desc: "new SMB" },
    { name: "Remove-SmbMapping", desc: "rm SMB" },
    { name: "Get-SmbServerConfiguration", desc: "SMB server" },
    { name: "Get-SmbClientConfiguration", desc: "SMB client" },
    { name: "Get-NetAdapterRss", desc: "RSS" },
    { name: "sc query bfe", desc: "BFE" },
    { name: "sc query wuauserv", desc: "WU" },
    { name: "sc config", desc: "config" },
    { name: "sc qc", desc: "qc" },
    { name: "sc qdescription", desc: "desc" },
    { name: "Get-Service -Name", desc: "service by name" },
    { name: "Restart-Service", desc: "restart" },
    { name: "tasklist /v", desc: "verbose" },
    { name: "tasklist /m", desc: "modules" },
    { name: "Stop-Process", desc: "stop process" },
  ]},
  { cat: "ویندوز تکمیلی B", cmds: [
    { name: "gpresult /h", desc: "GPO HTML" },
    { name: "gpupdate /target:computer", desc: "GPO PC" },
    { name: "gpupdate /target:user", desc: "GPO user" },
    { name: "nltest /dsgetsite", desc: "AD site" },
    { name: "nltest /whoami", desc: "security whoami" },
    { name: "echo %COMPUTERNAME%", desc: "computer" },
    { name: "echo %USERNAME%", desc: "username" },
    { name: "echo %USERDNSDOMAIN%", desc: "dns domain" },
    { name: "whoami /priv", desc: "privileges" },
    { name: "dsquery computer", desc: "AD PC" },
    { name: "dsquery user", desc: "AD user" },
    { name: "dsquery group", desc: "AD group" },
    { name: "Get-ADComputer", desc: "AD PC PS" },
    { name: "Get-ADUser", desc: "AD user PS" },
    { name: "wevtutil qe", desc: "query events" },
    { name: "perfmon", desc: "perfmon" },
    { name: "resmon", desc: "resmon" },
    { name: "inetcpl.cpl", desc: "internet options" },
    { name: "control netconnections", desc: "ncpa" },
    { name: "dxdiag", desc: "dxdiag" },
    { name: "DISM /Online /Cleanup-Image /ScanHealth", desc: "DISM" },
    { name: "powercfg /energy", desc: "energy" },
    { name: "powercfg /batteryreport", desc: "battery" },
    { name: "winsat formal", desc: "winsat" },
    { name: "certmgr.msc", desc: "cert mgr" },
    { name: "certutil -urlcache", desc: "urlcache" },
    { name: "Get-ChildItem Cert:", desc: "certs" },
    { name: "Get-NetIPsecQuickModeSA", desc: "IPsec QM" },
    { name: "rasphone", desc: "rasphone" },
    { name: "osi 1", desc: "Physical" },
    { name: "osi 2", desc: "Data Link" },
    { name: "osi 3", desc: "Network" },
    { name: "osi 4", desc: "Transport" },
    { name: "osi 5", desc: "Session" },
    { name: "osi 6", desc: "Presentation" },
    { name: "osi 7", desc: "Application" },
    { name: "load-balancing", desc: "LB" },
    { name: "ha", desc: "HA" },
    { name: "sdn", desc: "SDN" },
    { name: "vxlan", desc: "VXLAN" },
    { name: "eigrp", desc: "EIGRP" },
    { name: "rip", desc: "RIP" },
    { name: "gre", desc: "GRE" },
    { name: "dhcp-options", desc: "DHCP opts" },
    { name: "dnssec", desc: "DNSSEC" },
    { name: "cdp", desc: "CDP" },
    { name: "lldp", desc: "LLDP" },
    { name: "pagp", desc: "PAgP" },
    { name: "glbp", desc: "GLBP" },
    { name: "etherchannel", desc: "EtherChannel" },
    { name: "dynamic-arp-inspection", desc: "DAI" },
    { name: "ip-source-guard", desc: "IPSG" },
    { name: "ip link", desc: "ip link" },
    { name: "ss -s", desc: "socket stats" },
    { name: "route -n", desc: "route -n" },
    { name: "tracepath", desc: "tracepath" },
    { name: "mtr", desc: "mtr" },
    { name: "nmtui", desc: "nmtui" },
    { name: "resolvectl", desc: "resolvectl" },
    { name: "host", desc: "host" },
    { name: "netsh wlan show interfaces mode=bssid", desc: "BSSID" },
    { name: "whoami /groups", desc: "groups" },
    { name: "whoami /all", desc: "whoami all" },
  ]},
  { cat: "PowerShell Networking کامل", cmds: [
    { name: "Get-NetAdapter | Format-Table", desc: "جدول آداپتر" },
    { name: "Get-NetAdapter -Physical", desc: "فقط فیزیکی" },
    { name: "Get-NetIPAddress -AddressFamily IPv4", desc: "فقط IPv4" },
    { name: "Get-NetIPConfiguration -Detailed", desc: "پیکربندی جزئی" },
    { name: "Get-NetRoute -AddressFamily IPv4", desc: "روت IPv4" },
    { name: "Get-NetNeighbor -State Reachable", desc: "همسایه Reachable" },
    { name: "Get-NetTCPConnection -State Established", desc: "TCP برقرار" },
    { name: "Get-NetTCPConnection -LocalPort 445", desc: "پورت SMB" },
    { name: "Get-NetFirewallRule -Enabled True", desc: "قوانین فعال" },
    { name: "Get-NetFirewallRule -Direction Inbound", desc: "ورودی" },
    { name: "Get-DnsClientCache | Format-Table", desc: "کش DNS جدول" },
    { name: "Resolve-DnsName -Type MX", desc: "MX در PS" },
    { name: "Resolve-DnsName -Type AAAA", desc: "AAAA در PS" },
    { name: "Test-NetConnection -Port 443", desc: "تست پورت 443" },
    { name: "Test-NetConnection -TraceRoute", desc: "TNC + route" },
    { name: "Test-Connection -Count 4", desc: "ping PS" },
    { name: "Get-SmbShare | Format-Table", desc: "شیر SMB جدول" },
    { name: "Get-NetConnectionProfile | Select *", desc: "پروفایل کامل" },
    { name: "Get-NetAdapterBinding -ComponentID ms_tcpip", desc: "TCP/IP binding" },
    { name: "Get-NetIPsecMainModeSA", desc: "IPsec MM SA" },
    { name: "Get-NetIPsecQuickModeSA", desc: "IPsec QM SA" },
    { name: "Get-VpnConnection", desc: "VPNها" },
    { name: "Get-NetQosPolicy", desc: "سیاست QoS" },
    { name: "Get-NetLbfoTeam", desc: "NIC Team" },
    { name: "Find-NetRoute -RemoteIPAddress", desc: "مسیر تا IP" },
  ]},
];
