export const COMMAND_COUNT = 284;

export const COMMAND_CATALOG: { cat: string; cmds: { name: string; desc: string }[] }[] = [
  { cat: "عمومی", cmds: [
    { name: "help", desc: "راهنمای کامل" },
    { name: "help windows", desc: "دستورات ویندوز" },
    { name: "help network", desc: "دستورات شبکه" },
    { name: "help all", desc: "همه دستورات" },
    { name: "clear", desc: "پاک کردن صفحه" },
    { name: "cls", desc: "پاک کردن صفحه" },
    { name: "whoami", desc: "کاربر فعلی" },
    { name: "hostname", desc: "نام کامپیوتر" },
    { name: "ver", desc: "نسخه ویندوز" },
    { name: "winver", desc: "نسخه ویندوز GUI" },
    { name: "systeminfo", desc: "اطلاعات سیستم" },
    { name: "msinfo32", desc: "System Information" },
    { name: "date", desc: "تاریخ" },
    { name: "time", desc: "ساعت" },
    { name: "echo", desc: "چاپ متن" },
    { name: "set", desc: "متغیرهای محیطی" },
    { name: "lab-info", desc: "وضعیت لاب" },
    { name: "about-network", desc: "مفاهیم پایه شبکه" },
    { name: "cmd", desc: "یادآوری محیط CMD" },
    { name: "powershell", desc: "یادآوری محیط PowerShell" },
    { name: "exit", desc: "خروج از لاب" },
    { name: "title", desc: "عنوان پنجره" },
    { name: "color", desc: "رنگ کنسول" },
    { name: "prompt", desc: "تغییر پرامپت" },
  ]},
  { cat: "ipconfig و آداپتر", cmds: [
    { name: "ipconfig", desc: "پیکربندی IP" },
    { name: "ipconfig /all", desc: "جزئیات کامل" },
    { name: "ipconfig /release", desc: "آزاد کردن DHCP" },
    { name: "ipconfig /renew", desc: "تمدید DHCP" },
    { name: "ipconfig /flushdns", desc: "پاک کردن کش DNS" },
    { name: "ipconfig /displaydns", desc: "نمایش کش DNS" },
    { name: "ipconfig /registerdns", desc: "ثبت در DNS" },
    { name: "ipconfig /allcompartments", desc: "همه compartmentها" },
    { name: "ipconfig /release6", desc: "آزاد کردن IPv6" },
    { name: "ipconfig /renew6", desc: "تمدید IPv6" },
    { name: "getmac", desc: "آدرس MAC" },
    { name: "getmac /v", desc: "MAC با جزئیات" },
    { name: "getmac /fo list", desc: "MAC فرمت list" },
    { name: "getmac /fo csv", desc: "MAC فرمت csv" },
    { name: "getmac /s", desc: "MAC ریموت" },
  ]},
  { cat: "netsh interface", cmds: [
    { name: "netsh", desc: "مرکز netsh" },
    { name: "netsh interface show interface", desc: "لیست اینترفیس" },
    { name: "netsh interface ip show config", desc: "پیکربندی IP" },
    { name: "netsh interface ip show address", desc: "آدرس IP" },
    { name: "netsh interface ip show dns", desc: "DNS اینترفیس" },
    { name: "netsh interface ip show wins", desc: "WINS" },
    { name: "netsh interface ipv4 show route", desc: "روت IPv4" },
    { name: "netsh interface ipv4 show neighbors", desc: "همسایه‌ها" },
    { name: "netsh interface ipv4 show interfaces", desc: "اینترفیس IPv4" },
    { name: "netsh interface ipv6 show address", desc: "آدرس IPv6" },
    { name: "netsh interface ipv6 show route", desc: "روت IPv6" },
    { name: "netsh interface set interface", desc: "تنظیم اینترفیس" },
    { name: "netsh interface ip set address", desc: "IP استاتیک" },
    { name: "netsh interface ip set dns", desc: "تنظیم DNS" },
    { name: "netsh interface ip add address", desc: "افزودن IP" },
    { name: "netsh interface ip delete address", desc: "حذف IP" },
    { name: "netsh interface ip reset", desc: "ریست TCP/IP" },
    { name: "netsh interface ipv4 reset", desc: "ریست IPv4" },
    { name: "netsh interface portproxy show all", desc: "port proxy" },
    { name: "netsh interface tcp show global", desc: "تنظیمات TCP" },
  ]},
  { cat: "netsh wlan", cmds: [
    { name: "netsh wlan show profiles", desc: "پروفایل Wi-Fi" },
    { name: "netsh wlan show interfaces", desc: "وضعیت وای‌فای" },
    { name: "netsh wlan show networks", desc: "شبکه‌های در دسترس" },
    { name: "netsh wlan show drivers", desc: "درایور وای‌فای" },
    { name: "netsh wlan show profile name=", desc: "جزئیات پروفایل" },
    { name: "netsh wlan export profile", desc: "خروجی XML" },
    { name: "netsh wlan delete profile", desc: "حذف پروفایل" },
    { name: "netsh wlan connect", desc: "اتصال وای‌فای" },
    { name: "netsh wlan disconnect", desc: "قطع وای‌فای" },
    { name: "netsh wlan show wlanreport", desc: "گزارش وای‌فای" },
    { name: "netsh wlan set hostednetwork", desc: "hosted network" },
    { name: "netsh wlan start hostednetwork", desc: "شروع hotspot" },
    { name: "netsh wlan stop hostednetwork", desc: "توقف hotspot" },
  ]},
  { cat: "netsh firewall", cmds: [
    { name: "netsh advfirewall show allprofiles", desc: "وضعیت فایروال" },
    { name: "netsh advfirewall show domainprofile", desc: "Domain" },
    { name: "netsh advfirewall show privateprofile", desc: "Private" },
    { name: "netsh advfirewall show publicprofile", desc: "Public" },
    { name: "netsh advfirewall firewall show rule name=all", desc: "همه قوانین" },
    { name: "netsh advfirewall set allprofiles state on", desc: "فعال فایروال" },
    { name: "netsh advfirewall set allprofiles state off", desc: "غیرفعال" },
    { name: "netsh advfirewall reset", desc: "ریست فایروال" },
    { name: "netsh advfirewall firewall add rule", desc: "افزودن قانون" },
    { name: "netsh advfirewall firewall delete rule", desc: "حذف قانون" },
    { name: "netsh firewall show state", desc: "فایروال قدیمی" },
    { name: "netsh firewall show config", desc: "پیکربندی قدیمی" },
  ]},
  { cat: "اتصال و عیب‌یابی", cmds: [
    { name: "ping", desc: "تست ICMP" },
    { name: "ping -t", desc: "ping مداوم" },
    { name: "ping -n", desc: "تعداد پکت" },
    { name: "ping -l", desc: "اندازه پکت" },
    { name: "ping -a", desc: "resolve نام" },
    { name: "ping -4", desc: "فقط IPv4" },
    { name: "ping -6", desc: "فقط IPv6" },
    { name: "tracert", desc: "مسیریابی" },
    { name: "tracert -d", desc: "بدون DNS" },
    { name: "pathping", desc: "ping+tracert+loss" },
    { name: "nslookup", desc: "پرس‌وجوی DNS" },
    { name: "nslookup -type=A", desc: "رکورد A" },
    { name: "nslookup -type=AAAA", desc: "رکورد AAAA" },
    { name: "nslookup -type=MX", desc: "رکورد MX" },
    { name: "nslookup -type=NS", desc: "رکورد NS" },
    { name: "nslookup -type=TXT", desc: "رکورد TXT" },
    { name: "nslookup -type=CNAME", desc: "رکورد CNAME" },
    { name: "nslookup -type=SOA", desc: "رکورد SOA" },
    { name: "nslookup -type=PTR", desc: "رکورد PTR" },
    { name: "nslookup -type=SRV", desc: "رکورد SRV" },
    { name: "telnet", desc: "تست پورت" },
    { name: "Test-NetConnection", desc: "تست اتصال PS" },
    { name: "tnc", desc: "مخفف TNC" },
    { name: "Test-Connection", desc: "جایگزین ping PS" },
  ]},
  { cat: "ARP Route Netstat", cmds: [
    { name: "arp -a", desc: "جدول ARP" },
    { name: "arp -d", desc: "پاک کردن ARP" },
    { name: "arp -d *", desc: "پاک کردن همه" },
    { name: "arp -s", desc: "ARP استاتیک" },
    { name: "route print", desc: "جدول روت" },
    { name: "route print -4", desc: "روت IPv4" },
    { name: "route print -6", desc: "روت IPv6" },
    { name: "route add", desc: "افزودن روت" },
    { name: "route delete", desc: "حذف روت" },
    { name: "route change", desc: "تغییر روت" },
    { name: "netstat", desc: "اتصالات" },
    { name: "netstat -a", desc: "همه اتصالات" },
    { name: "netstat -an", desc: "عددی" },
    { name: "netstat -ano", desc: "با PID" },
    { name: "netstat -b", desc: "با نام برنامه" },
    { name: "netstat -e", desc: "آمار اترنت" },
    { name: "netstat -s", desc: "آمار پروتکل" },
    { name: "netstat -r", desc: "جدول روت" },
    { name: "netstat -p tcp", desc: "فقط TCP" },
    { name: "netstat -p udp", desc: "فقط UDP" },
  ]},
  { cat: "net commands", cmds: [
    { name: "net view", desc: "کامپیوترهای شبکه" },
    { name: "net view /domain", desc: "دامنه‌ها" },
    { name: "net share", desc: "شیرهای محلی" },
    { name: "net use", desc: "درایو map" },
    { name: "net user", desc: "کاربران" },
    { name: "net localgroup", desc: "گروه‌ها" },
    { name: "net localgroup administrators", desc: "اعضای Admins" },
    { name: "net accounts", desc: "سیاست رمز" },
    { name: "net session", desc: "نشست‌ها" },
    { name: "net statistics workstation", desc: "آمار WS" },
    { name: "net config workstation", desc: "پیکربندی WS" },
    { name: "net start", desc: "سرویس‌های فعال" },
    { name: "net stop", desc: "توقف سرویس" },
    { name: "net help", desc: "راهنمای net" },
    { name: "net time", desc: "زمان سرور" },
  ]},
  { cat: "DNS Client", cmds: [
    { name: "Resolve-DnsName", desc: "resolve در PS" },
    { name: "Get-DnsClient", desc: "تنظیمات DNS کلاینت" },
    { name: "Get-DnsClientServerAddress", desc: "آدرس سرور DNS" },
    { name: "Clear-DnsClientCache", desc: "پاک کردن کش" },
    { name: "Get-DnsClientCache", desc: "محتوای کش" },
    { name: "Set-DnsClientServerAddress", desc: "تنظیم DNS" },
    { name: "Register-DnsClient", desc: "ثبت مجدد" },
    { name: "nbtstat -n", desc: "نام‌های NetBIOS" },
    { name: "nbtstat -c", desc: "کش NetBIOS" },
    { name: "nbtstat -a", desc: "جدول نام ریموت" },
    { name: "nbtstat -r", desc: "آمار resolve" },
    { name: "nbtstat -R", desc: "ریلود کش" },
    { name: "nbtstat -RR", desc: "ثبت مجدد" },
  ]},
  { cat: "PowerShell Networking", cmds: [
    { name: "Get-NetAdapter", desc: "آداپترها" },
    { name: "Get-NetAdapterStatistics", desc: "آمار آداپتر" },
    { name: "Get-NetAdapterBinding", desc: "binding" },
    { name: "Enable-NetAdapter", desc: "فعال‌سازی" },
    { name: "Disable-NetAdapter", desc: "غیرفعال‌سازی" },
    { name: "Restart-NetAdapter", desc: "ریستارت آداپتر" },
    { name: "Get-NetIPAddress", desc: "آدرس‌های IP" },
    { name: "Get-NetIPConfiguration", desc: "پیکربندی کامل" },
    { name: "Get-NetIPInterface", desc: "اینترفیس IP" },
    { name: "New-NetIPAddress", desc: "IP جدید" },
    { name: "Remove-NetIPAddress", desc: "حذف IP" },
    { name: "Get-NetRoute", desc: "جدول روت" },
    { name: "New-NetRoute", desc: "روت جدید" },
    { name: "Remove-NetRoute", desc: "حذف روت" },
    { name: "Find-NetRoute", desc: "یافتن مسیر" },
    { name: "Get-NetNeighbor", desc: "همسایه‌ها" },
    { name: "Get-NetTCPConnection", desc: "اتصالات TCP" },
    { name: "Get-NetUDPEndpoint", desc: "endpoint UDP" },
    { name: "Get-NetFirewallRule", desc: "قوانین فایروال" },
    { name: "Get-NetFirewallProfile", desc: "پروفایل فایروال" },
    { name: "Enable-NetFirewallRule", desc: "فعال قانون" },
    { name: "Disable-NetFirewallRule", desc: "غیرفعال قانون" },
    { name: "New-NetFirewallRule", desc: "قانون جدید" },
    { name: "Get-NetConnectionProfile", desc: "پروفایل اتصال" },
    { name: "Get-SmbShare", desc: "شیر SMB" },
    { name: "Get-SmbConnection", desc: "اتصال SMB" },
    { name: "Get-SmbSession", desc: "نشست SMB" },
    { name: "Get-NetLbfoTeam", desc: "NIC Teaming" },
    { name: "Get-NetQosPolicy", desc: "QoS" },
  ]},
  { cat: "سرویس و فرآیند", cmds: [
    { name: "sc query", desc: "وضعیت سرویس" },
    { name: "sc query dnscache", desc: "DNS Client" },
    { name: "sc query dhcp", desc: "DHCP Client" },
    { name: "sc query nsi", desc: "NSI" },
    { name: "sc query netman", desc: "Network Connections" },
    { name: "sc query lanmanworkstation", desc: "Workstation" },
    { name: "sc query lanmanserver", desc: "Server" },
    { name: "sc query mpssvc", desc: "Windows Firewall" },
    { name: "sc start", desc: "شروع سرویس" },
    { name: "sc stop", desc: "توقف سرویس" },
    { name: "Get-Service", desc: "لیست سرویس PS" },
    { name: "Start-Service", desc: "شروع PS" },
    { name: "Stop-Service", desc: "توقف PS" },
    { name: "tasklist", desc: "فرآیندها" },
    { name: "tasklist /svc", desc: "فرآیند+سرویس" },
    { name: "taskkill", desc: "کشتن فرآیند" },
    { name: "Get-Process", desc: "فرآیندها PS" },
  ]},
  { cat: "دامنه AD و GPO", cmds: [
    { name: "gpresult /r", desc: "نتیجه GPO" },
    { name: "gpupdate /force", desc: "اعمال GPO" },
    { name: "nltest /dsgetdc:", desc: "یافتن DC" },
    { name: "nltest /dclist:", desc: "لیست DC" },
    { name: "whoami /groups", desc: "گروه‌ها" },
    { name: "whoami /all", desc: "همه اطلاعات" },
    { name: "klist", desc: "تیکت‌های Kerberos" },
    { name: "klist purge", desc: "پاک کردن تیکت" },
    { name: "setspn -L", desc: "لیست SPN" },
    { name: "Get-ADDomain", desc: "اطلاعات دامنه" },
    { name: "Get-ADDomainController", desc: "DCها" },
    { name: "repadmin /showrepl", desc: "replication" },
    { name: "echo %LOGONSERVER%", desc: "سرور لاگین" },
    { name: "echo %USERDOMAIN%", desc: "دامنه" },
  ]},
  { cat: "رویداد و عیب‌یابی پیشرفته", cmds: [
    { name: "eventvwr", desc: "Event Viewer" },
    { name: "Get-WinEvent", desc: "رویدادها PS" },
    { name: "wevtutil el", desc: "لیست لاگ‌ها" },
    { name: "ncpa.cpl", desc: "Network Connections GUI" },
    { name: "firewall.cpl", desc: "Firewall GUI" },
    { name: "services.msc", desc: "Services" },
    { name: "compmgmt.msc", desc: "Computer Management" },
    { name: "devmgmt.msc", desc: "Device Manager" },
    { name: "msconfig", desc: "System Configuration" },
    { name: "sfc /scannow", desc: "بررسی فایل سیستم" },
    { name: "chkdsk", desc: "بررسی دیسک" },
  ]},
  { cat: "امنیت و گواهی", cmds: [
    { name: "certutil -store", desc: "ذخیره گواهی" },
    { name: "Get-TlsCipherSuite", desc: "مجموعه رمز TLS" },
    { name: "Get-VpnConnection", desc: "اتصالات VPN" },
    { name: "Add-VpnConnection", desc: "افزودن VPN" },
    { name: "rasdial", desc: "شماره‌گیری VPN" },
    { name: "Get-BitLockerVolume", desc: "BitLocker" },
    { name: "manage-bde -status", desc: "وضعیت BitLocker" },
    { name: "Get-NetIPsecMainModeSA", desc: "IPsec SA" },
  ]},
  { cat: "آموزشی شبکه", cmds: [
    { name: "osi", desc: "مدل OSI" },
    { name: "packet-journey", desc: "مسیر بسته" },
    { name: "show-mac", desc: "جدول MAC" },
    { name: "switch-behavior", desc: "رفتار سوییچ" },
    { name: "domains", desc: "Collision/Broadcast" },
    { name: "subnet", desc: "محاسبه ساب‌نت" },
    { name: "private-ranges", desc: "RFC1918" },
    { name: "arp-how", desc: "فرآیند ARP" },
    { name: "tcp-handshake", desc: "Handshake" },
    { name: "dns-records", desc: "رکورد DNS" },
    { name: "dig", desc: "dig" },
    { name: "dhcp-dora", desc: "DORA" },
    { name: "security-zones", desc: "Zoneها" },
    { name: "ports", desc: "پورت‌های رایج" },
    { name: "vlan", desc: "VLAN" },
    { name: "nat", desc: "NAT" },
    { name: "acl", desc: "ACL" },
    { name: "stp", desc: "STP" },
    { name: "vpn", desc: "VPN" },
    { name: "proxy", desc: "Proxy" },
    { name: "firewall", desc: "فایروال" },
    { name: "wifi", desc: "Wi-Fi" },
    { name: "cable", desc: "کابل" },
    { name: "fiber", desc: "فیبر" },
    { name: "bandwidth", desc: "پهنای باند" },
    { name: "latency", desc: "تأخیر" },
    { name: "mtu", desc: "MTU" },
    { name: "qos", desc: "QoS" },
    { name: "bgp", desc: "BGP" },
    { name: "ospf", desc: "OSPF" },
    { name: "mpls", desc: "MPLS" },
    { name: "ipsec", desc: "IPsec" },
    { name: "ssl", desc: "SSL/TLS" },
    { name: "lacp", desc: "LACP" },
    { name: "hsrp", desc: "HSRP" },
    { name: "vrrp", desc: "VRRP" },
    { name: "port-security", desc: "Port Security" },
    { name: "dhcp-snooping", desc: "DHCP Snooping" },
  ]},
  { cat: "لینوکس شبکه مرجع", cmds: [
    { name: "ip addr", desc: "آدرس‌ها" },
    { name: "ip route", desc: "روت" },
    { name: "ip neigh", desc: "ARP لینوکس" },
    { name: "ss -tuln", desc: "سوکت‌ها" },
    { name: "ifconfig", desc: "ifconfig" },
    { name: "traceroute", desc: "traceroute" },
    { name: "nmcli", desc: "NetworkManager" },
    { name: "dig @8.8.8.8", desc: "dig با سرور" },
    { name: "tcpdump", desc: "tcpdump" },
    { name: "wireshark", desc: "Wireshark" },
  ]},
];
