import type { Chapter, Badge } from '../types';

export const BADGES: Badge[] = [
  { id: 'net-explorer', title: 'Network Explorer', description: 'اولین کوئست شبکه را کامل کردی', icon: '🌐', category: 'شروع', unlocked: false },
  { id: 'osi-master', title: 'OSI Master', description: 'مدل OSI را کامل یاد گرفتی', icon: '📶', category: 'مبانی', unlocked: false },
  { id: 'switch-pro', title: 'Switching Pro', description: 'کوئست‌های سوییچینگ را تمام کردی', icon: '🔀', category: 'لایه ۲', unlocked: false },
  { id: 'ip-ninja', title: 'IP Ninja', description: 'ساب‌نتینگ و آدرس‌دهی را مسلط شدی', icon: '🔢', category: 'لایه ۳', unlocked: false },
  { id: 'protocol-guru', title: 'Protocol Guru', description: 'ARP، TCP، UDP و ICMP را کامل کردی', icon: '📡', category: 'پروتکل', unlocked: false },
  { id: 'dns-hero', title: 'DNS Hero', description: 'سرویس‌های DNS و DHCP را یاد گرفتی', icon: '🗂️', category: 'سرویس', unlocked: false },
  { id: 'security-spec', title: 'Security Specialist', description: 'مبانی امنیت شبکه را کامل کردی', icon: '🛡️', category: 'امنیت', unlocked: false },
];

export const CHAPTERS: Chapter[] = [
  {
    id: 'ch1',
    number: 1,
    title: 'مبانی شبکه و مدل OSI',
    subtitle: 'از کابل تا اپلیکیشن',
    icon: '📡',
    description: 'انواع شبکه، مدل OSI هفت‌لایه، TCP/IP و مسیر حرکت یک بسته',
    levelRequired: 1,
    quests: [
      {
        id: 'q1-1',
        chapterId: 'ch1',
        title: 'آشنایی با انواع شبکه',
        category: 'مبانی',
        level: 1,
        xpReward: 50,
        difficulty: 'مقدماتی',
        description: 'LAN، WAN، MAN و Intranet را بشناس و تفاوت‌شان را درک کن.',
        targetInstruction: 'دستور help را اجرا کن و سپس با دستور about-network اطلاعات پایه را ببین.',
        suggestedCommands: ['help', 'about-network', 'osi'],
        hints: ['از دستور help شروع کن', 'about-network خلاصه خوبی می‌دهد'],
        objectives: [
          { id: 'obj1', text: 'دستور help را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /help/i },
          { id: 'obj2', text: 'دستور about-network را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /about-network/i },
        ],
        solutionExplanation: 'با help لیست دستورات را می‌بینی و about-network توضیح کوتاهی از مفاهیم پایه شبکه می‌دهد.',
        badgeRewardId: 'net-explorer',
      },
      {
        id: 'q1-2',
        chapterId: 'ch1',
        title: 'مدل OSI — هفت لایه',
        category: 'مبانی',
        level: 1,
        xpReward: 80,
        difficulty: 'مقدماتی',
        description: 'هر لایه OSI چه کاری انجام می‌دهد و PDU مربوط به آن چیست؟',
        targetInstruction: 'دستور osi را اجرا کن و لایه‌ها را بررسی کن. سپس osi 3 را برای جزئیات لایه شبکه بزن.',
        suggestedCommands: ['osi', 'osi 3', 'osi 4'],
        hints: ['osi بدون آرگومان همه لایه‌ها را نشان می‌دهد', 'با شماره لایه جزئیات بیشتری می‌گیری'],
        objectives: [
          { id: 'obj1', text: 'دستور osi را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /^osi\s*$/i },
          { id: 'obj2', text: 'جزئیات لایه ۳ (Network) را ببین', completed: false, checkType: 'command_run', expectedCommand: /osi\s+3/i },
        ],
        solutionExplanation: 'مدل OSI چارچوب استانداردی برای درک ارتباطات شبکه است. لایه ۳ مسئول آدرس‌دهی منطقی (IP) و مسیریابی است.',
        badgeRewardId: 'osi-master',
      },
      {
        id: 'q1-3',
        chapterId: 'ch1',
        title: 'مسیر یک بسته (Packet Journey)',
        category: 'مبانی',
        level: 1,
        xpReward: 70,
        difficulty: 'مقدماتی',
        description: 'یک بسته از اپلیکیشن تا کابل چه مسیری طی می‌کند؟',
        targetInstruction: 'دستور packet-journey را اجرا کن.',
        suggestedCommands: ['packet-journey'],
        hints: ['فقط یک دستور کافی است'],
        objectives: [
          { id: 'obj1', text: 'packet-journey را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /packet-journey/i },
        ],
        solutionExplanation: 'بسته از لایه Application شروع می‌کند، در هر لایه هدر اضافه می‌شود (Encapsulation) و در مقصد برعکس (Decapsulation) انجام می‌شود.',
      },
    ],
  },
  {
    id: 'ch2',
    number: 2,
    title: 'اترنت و سوییچینگ',
    subtitle: 'لایه ۲ در عمل',
    icon: '🔀',
    description: 'فریم اترنت، جدول MAC، رفتار سوییچ و Collision/Broadcast Domain',
    levelRequired: 1,
    quests: [
      {
        id: 'q2-1',
        chapterId: 'ch2',
        title: 'جدول MAC و یادگیری',
        category: 'سوییچینگ',
        level: 1,
        xpReward: 90,
        difficulty: 'مقدماتی',
        description: 'سوییچ چگونه آدرس‌های MAC را یاد می‌گیرد و فریم را فوروارد می‌کند؟',
        targetInstruction: 'دستورات show-mac و switch-behavior را اجرا کن.',
        suggestedCommands: ['show-mac', 'switch-behavior'],
        hints: ['show-mac جدول نمونه را نشان می‌دهد'],
        objectives: [
          { id: 'obj1', text: 'show-mac را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /show-mac/i },
          { id: 'obj2', text: 'switch-behavior را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /switch-behavior/i },
        ],
        solutionExplanation: 'سوییچ با دیدن Source MAC فریم‌های ورودی، جدول CAM را پر می‌کند و بر اساس Destination MAC تصمیم می‌گیرد: Forward، Flood یا Filter.',
        badgeRewardId: 'switch-pro',
      },
      {
        id: 'q2-2',
        chapterId: 'ch2',
        title: 'Collision و Broadcast Domain',
        category: 'سوییچینگ',
        level: 2,
        xpReward: 80,
        difficulty: 'متوسط',
        description: 'تفاوت دامنه برخورد و دامنه پخش را درک کن.',
        targetInstruction: 'دستور domains را اجرا کن.',
        suggestedCommands: ['domains'],
        hints: ['یک دستور کافی است'],
        objectives: [
          { id: 'obj1', text: 'domains را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /domains/i },
        ],
        solutionExplanation: 'هر پورت سوییچ یک Collision Domain جداگانه است. کل VLAN یک Broadcast Domain مشترک دارد.',
      },
    ],
  },
  {
    id: 'ch3',
    number: 3,
    title: 'IPv4، IPv6 و ساب‌نتینگ',
    subtitle: 'آدرس‌دهی منطقی',
    icon: '🔢',
    description: 'ساختار آدرس، CIDR، VLSM و طراحی طرح آدرس سازمانی',
    levelRequired: 2,
    quests: [
      {
        id: 'q3-1',
        chapterId: 'ch3',
        title: 'محاسبه ساب‌نت ساده',
        category: 'آدرس‌دهی',
        level: 2,
        xpReward: 100,
        difficulty: 'متوسط',
        description: 'با داشتن شبکه و تعداد هاست مورد نیاز، ساب‌نت مناسب را پیدا کن.',
        targetInstruction: 'دستور subnet 192.168.10.0/24 50 را اجرا کن تا ببینی چگونه محاسبه می‌شود.',
        suggestedCommands: ['subnet', 'ipcalc'],
        hints: ['آرگومان‌ها: شبکه و تعداد هاست'],
        objectives: [
          { id: 'obj1', text: 'subnet را با آرگومان اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /subnet/i },
        ],
        solutionExplanation: 'برای ۵۰ هاست به ۶ بیت هاست نیاز داریم (۲^۶=۶۴). پس mask می‌شود /26.',
        badgeRewardId: 'ip-ninja',
      },
      {
        id: 'q3-2',
        chapterId: 'ch3',
        title: 'آدرس‌های خصوصی و APIPA',
        category: 'آدرس‌دهی',
        level: 1,
        xpReward: 60,
        difficulty: 'مقدماتی',
        description: 'محدوده‌های RFC1918 و آدرس‌های لینک‌لوکال را بشناس.',
        targetInstruction: 'دستور private-ranges را اجرا کن.',
        suggestedCommands: ['private-ranges'],
        hints: ['یک دستور'],
        objectives: [
          { id: 'obj1', text: 'private-ranges را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /private-ranges/i },
        ],
        solutionExplanation: '۱۰.۰.۰.۰/۸، ۱۷۲.۱۶.۰.۰/۱۲ و ۱۹۲.۱۶۸.۰.۰/۱۶ آدرس‌های خصوصی هستند. APIPA محدوده ۱۶۹.۲۵۴.۰.۰/۱۶ است.',
      },
    ],
  },
  {
    id: 'ch4',
    number: 4,
    title: 'ARP، ICMP، TCP و UDP',
    subtitle: 'پروتکل‌های حیاتی',
    icon: '📡',
    description: 'نحوه کار ARP، پیام‌های ICMP، handshake تی‌سی‌پی و مقایسه TCP/UDP',
    levelRequired: 2,
    quests: [
      {
        id: 'q4-1',
        chapterId: 'ch4',
        title: 'ARP در عمل',
        category: 'پروتکل',
        level: 2,
        xpReward: 90,
        difficulty: 'متوسط',
        description: 'فرآیند Request/Reply و جدول ARP را ببین.',
        targetInstruction: 'دستورات arp و arp-how را اجرا کن.',
        suggestedCommands: ['arp', 'arp-how'],
        hints: ['arp جدول نمونه را نشان می‌دهد'],
        objectives: [
          { id: 'obj1', text: 'arp را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /^arp\s*$/i },
          { id: 'obj2', text: 'arp-how را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /arp-how/i },
        ],
        solutionExplanation: 'وقتی IP مقصد در همان subnet باشد ولی MAC آن را ندانیم، ARP Request پخش می‌شود و صاحب IP با Reply پاسخ می‌دهد.',
        badgeRewardId: 'protocol-guru',
      },
      {
        id: 'q4-2',
        chapterId: 'ch4',
        title: 'TCP Three-way Handshake',
        category: 'پروتکل',
        level: 2,
        xpReward: 100,
        difficulty: 'متوسط',
        description: 'فرآیند برقراری اتصال TCP را قدم‌به‌قدم ببین.',
        targetInstruction: 'دستور tcp-handshake را اجرا کن.',
        suggestedCommands: ['tcp-handshake'],
        hints: ['یک دستور'],
        objectives: [
          { id: 'obj1', text: 'tcp-handshake را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /tcp-handshake/i },
        ],
        solutionExplanation: 'SYN → SYN-ACK → ACK. این سه مرحله اتصال قابل‌اطمینان را برقرار می‌کند.',
      },
    ],
  },
  {
    id: 'ch5',
    number: 5,
    title: 'DNS و DHCP',
    subtitle: 'سرویس‌های حیاتی شبکه',
    icon: '🗂️',
    description: 'رکوردهای DNS، فرآیند DORA و تنظیمات سازمانی',
    levelRequired: 3,
    quests: [
      {
        id: 'q5-1',
        chapterId: 'ch5',
        title: 'رکوردهای DNS',
        category: 'سرویس',
        level: 2,
        xpReward: 80,
        difficulty: 'متوسط',
        description: 'A، AAAA، CNAME، MX، NS و PTR را بشناس.',
        targetInstruction: 'دستور dns-records را اجرا کن و سپس dig example.com را شبیه‌سازی کن.',
        suggestedCommands: ['dns-records', 'dig'],
        hints: ['dig با دامنه کار می‌کند'],
        objectives: [
          { id: 'obj1', text: 'dns-records را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /dns-records/i },
          { id: 'obj2', text: 'dig را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /dig/i },
        ],
        solutionExplanation: 'A برای IPv4، AAAA برای IPv6، MX برای ایمیل و CNAME برای نام مستعار استفاده می‌شود.',
        badgeRewardId: 'dns-hero',
      },
      {
        id: 'q5-2',
        chapterId: 'ch5',
        title: 'فرآیند DHCP — DORA',
        category: 'سرویس',
        level: 2,
        xpReward: 90,
        difficulty: 'متوسط',
        description: 'Discover، Offer، Request، Acknowledge را درک کن.',
        targetInstruction: 'دستور dhcp-dora را اجرا کن.',
        suggestedCommands: ['dhcp-dora'],
        hints: ['یک دستور'],
        objectives: [
          { id: 'obj1', text: 'dhcp-dora را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /dhcp-dora/i },
        ],
        solutionExplanation: 'کلاینت با Broadcast درخواست می‌کند، سرور پیشنهاد می‌دهد، کلاینت درخواست می‌کند و سرور تأیید نهایی را می‌فرستد.',
      },
    ],
  },
  {
    id: 'ch6',
    number: 6,
    title: 'امنیت شبکه پایه',
    subtitle: 'محافظت از زیرساخت',
    icon: '🛡️',
    description: 'سگمنت‌بندی، ACL، فایروال و اصول دفاع در عمق',
    levelRequired: 3,
    quests: [
      {
        id: 'q6-1',
        chapterId: 'ch6',
        title: 'سگمنت‌بندی و Zoneها',
        category: 'امنیت',
        level: 3,
        xpReward: 110,
        difficulty: 'پیشرفته',
        description: 'چرا Users، Servers، DMZ و Management را جدا می‌کنیم؟',
        targetInstruction: 'دستور security-zones را اجرا کن.',
        suggestedCommands: ['security-zones'],
        hints: ['یک دستور'],
        objectives: [
          { id: 'obj1', text: 'security-zones را اجرا کن', completed: false, checkType: 'command_run', expectedCommand: /security-zones/i },
        ],
        solutionExplanation: 'جداسازی منطقی باعث محدود شدن شعاع آسیب و اعمال سیاست‌های امنیتی دقیق‌تر می‌شود.',
        badgeRewardId: 'security-spec',
      },
    ],
  },
];

export function getLevelTitle(level: number): string {
  if (level >= 10) return 'معمار شبکه';
  if (level >= 7) return 'مهندس ارشد';
  if (level >= 5) return 'ادمین شبکه';
  if (level >= 3) return 'تکنسین';
  return 'کارآموز شبکه';
}

export function xpForNextLevel(level: number): number {
  return level * 150;
}
